# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  submodules: true
- task: Cache@2
  displayName: "Cache vcpkg's artifacts"
  inputs:
    key: '"$(Build.SourcesDirectory)/vcpkg.txt" | "$(Build.SourcesDirectory)/.git/modules/lib/vcpkg/HEAD" | "$(Agent.OS)"'
    path: '$(Build.SourcesDirectory)/lib/vcpkg'
- task: run-vcpkg@0
  displayName: 'Run vcpkg'
  inputs:
    vcpkgArguments: '@$(Build.SourcesDirectory)/vcpkg.txt'
    vcpkgDirectory: $(Build.SourcesDirectory)/lib/vcpkg
- task: run-cmake@0
  inputs:
    cmakeListsOrSettingsJson: 'CMakeListsTxtBasic'
    useVcpkgToolchainFile: true
    cmakeBuildType: 'RelWithDebInfo'
    cmakeGenerator: 'UnixMakefiles'